### ISSUE TITLE
Any plans in adding support for Smartphones?

### ISSUE THREAD

**Issue by AlexisWilke** [ozh/ozh-tweet-archive-theme#4]
Right now the theme works beautifully, except that on smartphone the full width is shown (or an attempt at such at least) and it does not work well.

There are many ways to handle that, obviously, and I could do my own version and I can share back too... but wanted to know whether you were going to eventually work on such.

**Comment by ozh** [comment]
No plans on adding anything to this, sorry :)

**Comment by AlexisWilke** [comment]
No problem, the existing code is already marvelous!
